import "./globals.css";
import styles from "@/app/components/header"

export const metadata = {
  title: "alun. hillary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <header></header>
        {children}
      </body>
    </html>
  );
}
